name: flutter_hello_plugin
description: A new Flutter plugin.
version: 0.0.1
author: York
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    androidPackage: com.ykunit.flutterhelloplugin
    pluginClass: FlutterhellopluginPlugin
  assets:
    # 若资源目录放在根目录下，则资源的声明既可使用目录声明的方式，也可使用根资源文件声明的方式
    # 但是若当前是package/plugin工程，则上层应用在访问这些资源时，必须指定包名
    - images/test_only_main_asset_1.png
    - images/test_asset_variants/
    # 若资源目录放在lib目录下，则资源的声明只可使用包资源文件声明的方式
    - packages/flutter_hello_plugin/images2/test_only_main_asset_2.png
    - packages/flutter_hello_plugin/images2/test_asset_variants/test_png_variant_2.png


