name: flutter_hello_plugin
description: A new Flutter plugin.
version: 0.0.1
author: York
homepage: 
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  r_dart_library: 0.4.0-nullsafety.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    androidPackage: com.ykunit.flutterhelloplugin
    pluginClass: FlutterHelloPlugin
  assets:
  - assets/images/test_asset_variants/test_png_variant_1.png
  - assets/images/test_only_main_asset_1.png
  - packages/flutter_hello_plugin/assets/images/test_asset_variants/test_png_variant_2.png
  - packages/flutter_hello_plugin/assets/images/test_only_main_asset_2.png
  - assets/texts/test.json
  - packages/flutter_hello_plugin/assets/texts/test.yaml
  fonts:
  - family: Amiri
    fonts:
    - asset: packages/flutter_hello_plugin/assets/fonts/Amiri/Amiri-Bold.ttf
    - asset: packages/flutter_hello_plugin/assets/fonts/Amiri/Amiri-BoldItalic.ttf
    - asset: packages/flutter_hello_plugin/assets/fonts/Amiri/Amiri-Italic.ttf
    - asset: packages/flutter_hello_plugin/assets/fonts/Amiri/Amiri-Regular.ttf
  - family: Baloo_Thambi_2
    fonts:
    - asset: assets/fonts/Baloo_Thambi_2/BalooThambi2-Bold.ttf
    - asset: assets/fonts/Baloo_Thambi_2/BalooThambi2-ExtraBold.ttf
    - asset: assets/fonts/Baloo_Thambi_2/BalooThambi2-Medium.ttf
    - asset: assets/fonts/Baloo_Thambi_2/BalooThambi2-Regular.ttf
    - asset: assets/fonts/Baloo_Thambi_2/BalooThambi2-SemiBold.ttf
  - family: Dan_Zhai_Hang_Shu_Cai
    fonts:
    - asset: packages/flutter_hello_plugin/assets/fonts/Dan_Zhai_Hang_Shu_Cai/Dan_Zhai_Hang_Shu_Cai.ttc
  - family: Liu_Jian_Mao_Cao
    fonts:
    - asset: assets/fonts/Liu_Jian_Mao_Cao/LiuJianMaoCao-Regular.ttf
  - family: Lobster
    fonts:
    - asset: assets/fonts/Lobster/Lobster-Regular.ttf
  - family: Pacifico
    fonts:
    - asset: packages/flutter_hello_plugin/assets/fonts/Pacifico/Pacifico-Regular.ttf
  - family: Sky_IconFont
    fonts:
    - asset: assets/fonts/Sky_IconFont/iconfont.ttf
  - family: YorkFish_IconFont
    fonts:
    - asset: packages/flutter_hello_plugin/assets/fonts/YorkFish_IconFont/iconfont.ttf
flr:
  core_version: 3.2.0
  dartfmt_line_length: 100
  assets:
  - assets/images
  - assets/texts
  - lib/assets/images
  - lib/assets/texts
  fonts:
  - assets/fonts
  - lib/assets/fonts
